<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>iComputer</title>';
echo '<link rel="stylesheet" href="css/style.css">';
echo '<link rel="shortcut icon" href="/img/favicon.ico" type="image/ico">';
echo '';

echo '</head>';
echo '<body>';
echo '<header>';
echo '<div class="header-container">';
echo '<a class="logo" href="#"><div class="logo-span">&lt;i<span>Computer</span>/&gt;</div></a>';
echo '<div class="search"><input type="text" placeholder="Enter the product you are looking for"><input type="submit" value="search"></div>';
echo '<div class="person"><a href="#">Enter</a> <div class="delimiter"></div> <a href="#">Registration</a></div>';
echo '</div>';
echo '</header>';
echo '<div class="categories">';
echo '<div class="categories-item">';
echo '<div class="ci-name">Producer:</div>';
echo '<div class="ci-blocks">';
echo '<div class="ci-block">Apple</div>';
echo '<div class="ci-block">Alza.sk</div>';
echo '<div class="ci-block">Datart.sh</div>';
echo '<div class="ci-block">Datacomp.sk</div>';
echo '<div class="ci-block">Alta</div>';
echo '<div class="ci-block">Avalon</div>';
echo '<div class="ci-block">Lenovo</div>';
echo '<div class="ci-block">ACER</div>';
echo '<div class="ci-block">ASUS</div>';
echo '<div class="ci-block">Dell</div>';
echo '</div>';
echo '</div>';
echo '<div class="hor-delimiter"></div>';
echo '<div class="categories-item">';
echo '<div class="ci-name">Destination:</div>';
echo '<div class="ci-blocks">';
echo '<div class="ci-block">Office</div>';
echo '<div class="ci-block">School</div>';
echo '<div class="ci-block">Gaming</div>';
echo '</div>';
echo '</div>';
echo '<div class="hor-delimiter"></div>';
echo '<div class="categories-item">';
echo '<div class="ci-name">Type:</div>';
echo '<div class="ci-blocks">';
echo '<div class="ci-block">PC</div>';
echo '<div class="ci-block">Notebook</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="sort-by">';
echo '<span>Sort:</span>';
echo '<div class="select">Last:</div>';
echo '</div>';
echo '<div class="hor-delimiter"></div>';
echo '<div class="market-item">';
echo '';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
?>
